### ISSUE TITLE
Error 1.18.2 (papermc)

### ISSUE THREAD

**Issue by SwordfishBE** [bush-did-711/instantdeepslate-plugin#1]
Error with paper 1.18.2 (git-Paper-234 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT))

[16:25:26 INFO]: [instantdeepslate] Loading instantdeepslate v1.0.0
[16:25:26 ERROR]: [InstantDeepslate] Could not get block properties for block.minecraft.deepslate
java.lang.ClassCastException: class net.minecraft.resources.MinecraftKey cannot be cast to class net.minecraft.world.level.block.state.BlockBase$Info (net.minecraft.resources.MinecraftKey and net.minecraft.world.level.block.state.BlockBase$Info are in unnamed module of loader java.net.URLClassLoader @661972b0)
        at me.bush.instantdeepslate.BlockTweak.getBlockProperties(BlockTweak.java:63) ~[instantdeepslate-1.0.0-plugin.jar:?]
        at me.bush.instantdeepslate.BlockTweak.<init>(BlockTweak.java:29) ~[instantdeepslate-1.0.0-plugin.jar:?]
        at me.bush.instantdeepslate.TweakRegistry.addTweak(TweakRegistry.java:50) ~[instantdeepslate-1.0.0-plugin.jar:?]
        at me.bush.instantdeepslate.TweakRegistry.<init>(TweakRegistry.java:13) ~[instantdeepslate-1.0.0-plugin.jar:?]
        at me.bush.instantdeepslate.InstantDeepslate.onLoad(InstantDeepslate.java:13) ~[instantdeepslate-1.0.0-plugin.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by bush-did-711** [comment]
It seems like 1.18.2 made some changes that affected the obfuscated names of the fields we are trying to change. I may come back to this plugin if I play Minecraft more, but for now you would probably have to verify that the field names are correct by checking them against the mojang mappings.

Ideally this whole plugin should be rewritten to use mixin accessors instead of reflection.

**Comment by bush-did-711** [comment]
> Unfortunately above my knowledge level ;)

i just decided to update it, ill post the release in a few minutes
